# Generated by Django 4.2.7 on 2023-11-08 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("file_sharing_system", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="is_text_file",
        ),
    ]
