# Generated by Django 4.2.7 on 2023-11-09 09:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_sharing_system", "0002_remove_file_is_text_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="directory",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="drive",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="file",
            name="id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
