# Generated by Django 4.2.7 on 2023-11-09 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_sharing_system', '0003_alter_directory_id_alter_drive_id_alter_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='drive',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
