# Generated by Django 4.2.7 on 2023-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_sharing_system", "0005_alter_directory_id_alter_drive_id_alter_file_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
